import type { IUser } from '../../types/user';

export const UserActionTypes = {
	CHECK_EMAIL_START: 'CHECK_EMAIL_START',
	CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
	CHECK_EMAIL_FAILURE: 'CHECK_EMAIL_FAILURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
	VERIFY_CODE_START: 'VERIFY_CODE_START',
	VERIFY_CODE_SUCCESS: 'VERIFY_CODE_SUCCESS',
	VERIFY_CODE_FAILURE: 'VERIFY_CODE_FAILURE',
	REFRESH_TOKEN_START: 'REFRESH_TOKEN_START',
	REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
	REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SIGN_OUT: 'SIGN_OUT',
	USER_ERROR_CLEAR: 'USER_ERROR_CLEAR',
	CLEAR_USER_STATE: 'CLEAR_USER_STATE',
};

export interface IUserState {
	currentUser: IUser | null;
	isFetching: boolean;
	signInEmail: string;
	userError: string;
}
