export enum _Enum {
    AD = 'AD', // Andorra
    AL = 'AL', // Albania
    AT = 'AT', // Austria
    BA = 'BA', // Bosnia and Herzegovina
    BE = 'BE', // Belgium
    BG = 'BG', // Bulgaria
    BY = 'BY', // Belarus
    CH = 'CH', // Switzerland
    CY = 'CY', // Cyprus
    CZ = 'CZ', // Czech Republic
    DE = 'DE', // Germany
    DK = 'DK', // Denmark
    EE = 'EE', // Estonia
    ES = 'ES', // Spain
    FI = 'FI', // Finland
    FR = 'FR', // France
    GB = 'GB', // United Kingdom
    GR = 'GR', // Greece
    HR = 'HR', // Croatia
    HU = 'HU', // Hungary
    IE = 'IE', // Ireland
    IS = 'IS', // Iceland
    IT = 'IT', // Italy
    LI = 'LI', // Liechtenstein
    LT = 'LT', // Lithuania
    LU = 'LU', // Luxembourg
    LV = 'LV', // Latvia
    MC = 'MC', // Monaco
    MD = 'MD', // Moldova
    ME = 'ME', // Montenegro
    MK = 'MK', // North Macedonia
    MT = 'MT', // Malta
    NL = 'NL', // Netherlands
    NO = 'NO', // Norway
    PL = 'PL', // Poland
    PT = 'PT', // Portugal
    RO = 'RO', // Romania
    RS = 'RS', // Serbia
    SE = 'SE', // Sweden
    SI = 'SI', // Slovenia
    SK = 'SK', // Slovakia
    SM = 'SM', // San Marino
    UA = 'UA', // Ukraine
    VA = 'VA', // Vatican City
}
