export namespace Game {
    export enum STATUS_ENUM {
        CREATED = 'CREATED',
        STARTED = 'STARTED',
        CANCELLED = 'CANCELLED',
        FINISHED = 'FINISHED',
    }

    export enum STAGE_ENUM {
        INTRODUCTION = 'INTRODUCTION',
        INTRODUCTION_QUESTIONS = 'INTRODUCTION_QUESTIONS',
        THEORETICAL_PART = 'THEORETICAL_PART',
        CASE_STUDIES = 'CASE_STUDIES',
        INTERACTIVE_QUESTIONS = 'INTERACTIVE_QUESTIONS',
        SUMMARIZE_QUESTIONS = 'SUMMARIZE_QUESTIONS',
        SUMMARIZE_MODULE = 'SUMMARIZE_MODULE',
    }
}

export namespace Module {
    export enum STATUS_ENUM {
        COMPLETED = 'COMPLETED',
        NOT_STARTED = 'NOT_STARTED',
        PENDING = 'PENDING',
    }
}

export namespace Question {
    export enum TYPES_ENUM {
        CONTENT_TEXT = 'CONTENT_TEXT',
        CONTENT_VIDEO = 'CONTENT_VIDEO',
        FIT_TILES = 'FIT_TILES',
        MULTI_CHOOSE = 'MULTI_CHOOSE',
        SELECT_CORRECT_ANSWER = 'SELECT_CORRECT_ANSWER',
        SINGLE_CHOOSE = 'SINGLE_CHOOSE',
        TRUE_FALSE = 'TRUE_FALSE',
    }

    export const PLAYABLE_QUESTION_TYPES: TYPES_ENUM[] = [TYPES_ENUM.FIT_TILES, TYPES_ENUM.MULTI_CHOOSE, TYPES_ENUM.SELECT_CORRECT_ANSWER, TYPES_ENUM.SINGLE_CHOOSE, TYPES_ENUM.TRUE_FALSE];

    export enum QUESTION_MEDIA_TYPES_ENUM {
        PHOTO = 'PHOTO',
        VIDEO = 'VIDEO',
    }
}
